-- 제약조건 
-- SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_CONSTRAINTS;
-- 기본키
--ALTER TABLE 테이블명 
--ADD CONSTRAINT 제약조건명 PRIMARY KEY(기본키로 지정할 컬럼)
DROP TABLE PERSON;
CREATE TABLE PERSON(	
    PID CHAR(4),
    PNAME VARCHAR2(30 BYTE), 
    AGE NUMBER(3,0)
);
ALTER TABLE PERSON ADD CONSTRAINT PERSON_PID_PK
PRIMARY KEY(PID);
SELECT * FROM USER_CONSTRAINTS;
CREATE TABLE PERSON(	
    PID CHAR(4),
    PNAME VARCHAR2(30 BYTE), 
    AGE NUMBER(3,0),
    CONSTRAINT PERSON_PID_PK PRIMARY KEY(PID)
);
--샘플데이터
INSERT INTO PERSON VALUES('0001','홍길동',20);
INSERT INTO PERSON VALUES('0002','김길동',30);
INSERT INTO PERSON VALUES('0003','이길동',40);
INSERT INTO PERSON VALUES('0004','박길동',50);
-- 외래키
--ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건명 
--FOREIGN KEY(외래키 지정할 컬럼명) 
--REFERENCES 외래키로연결될테이블명(참조할 테이블의 기본키)
--[ON DELETE CASCADE] | [ON DELETE RESTRICT] | [ON DELETE SET NULL]
CREATE TABLE PERSON_ORDER(
	P_ORDER_NO NUMBER(5),
	P_ORDER_MEMO VARCHAR2(300),
	PID CHAR(4)
);
--PERSON_ORDER에 P_ORDER_NO를 기본키로 작성
ALTER TABLE PERSON_ORDER ADD CONSTRAINT PERSON_ORDER_PO_NO_PK
PRIMARY KEY(P_ORDER_NO);
SELECT * FROM USER_CONSTRAINTS;
--PERSON_ORDER에 PID를 외래키 설정, PERSON에 있는 PID와 연결
ALTER TABLE PERSON_ORDER ADD CONSTRAINT PERSON_ORDER_PID_FK
FOREIGN KEY(PID) REFERENCES PERSON(PID); -- ON DELETE RESTRICT

INSERT INTO PERSON_ORDER VALUES(1, '지시 내용', '0001');
INSERT INTO PERSON_ORDER VALUES(2, '지시 내용', '0002');
INSERT INTO PERSON_ORDER VALUES(3, '지시 내용', '0003');
--에러, PERSON 테이블에 해당 PID 값이 없을때 --> 참조 무결성
INSERT INTO PERSON_ORDER VALUES(4, '지시 내용', '0005');
--PERSON 테이블에 PID가 0001인 데이터를 삭제 -> RESTRICT는 자식 레코드가 있으면 멈춤
DELETE FROM PERSON WHERE PID LIKE '0001';
--부모 레코드를 지우기전에 자식 레코드를 먼저 삭제
DELETE FROM PERSON_ORDER WHERE PID LIKE '0001';
--PERSON_ORDER에 외래키 제약조건 삭제
ALTER TABLE PERSON_ORDER DROP CONSTRAINT PERSON_ORDER_PID_FK;
--외래키 지정시 ON DELETE CASCADE 지정
ALTER TABLE PERSON_ORDER ADD CONSTRAINT PERSON_ORDER_PID_FK
FOREIGN KEY(PID) REFERENCES PERSON(PID) ON DELETE CASCADE;

SELECT * FROM PERSON_ORDER;
DELETE FROM PERSON WHERE PID LIKE '0002';








