-- 제약조건 
-- SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_CONSTRAINTS;
-- 기본키
--ALTER TABLE 테이블명 
--ADD CONSTRAINT 제약조건명 PRIMARY KEY(기본키로 지정할 컬럼)
DROP TABLE PERSON;
CREATE TABLE PERSON(	
    PID CHAR(4),
    PNAME VARCHAR2(30 BYTE), 
    AGE NUMBER(3,0)
);
ALTER TABLE PERSON ADD CONSTRAINT PERSON_PID_PK
PRIMARY KEY(PID);
SELECT * FROM USER_CONSTRAINTS;
CREATE TABLE PERSON(	
    PID CHAR(4),
    PNAME VARCHAR2(30 BYTE), 
    AGE NUMBER(3,0),
    CONSTRAINT PERSON_PID_PK PRIMARY KEY(PID)
);
--샘플데이터
INSERT INTO PERSON VALUES('0001','홍길동',20);
INSERT INTO PERSON VALUES('0002','김길동',30);
INSERT INTO PERSON VALUES('0003','이길동',40);
INSERT INTO PERSON VALUES('0004','박길동',50);
-- 외래키




