--조인
CREATE TABLE A(
	CODE CHAR(1),
	VAL NUMBER(1)
);
CREATE TABLE B(
	CODE CHAR(1),
	UNIT CHAR(1)
);
INSERT INTO A VALUES('A',1);
INSERT INTO A VALUES('B',2);
INSERT INTO A VALUES('C',3);
INSERT INTO A VALUES('D',4);

INSERT INTO B VALUES('A','+');
INSERT INTO B VALUES('B','-');
INSERT INTO B VALUES('C','*');
INSERT INTO B VALUES('F','/');

SELECT * FROM A;
SELECT * FROM B;

--동일 조인
SELECT A.CODE, A.VAL, B.CODE, B.UNIT 
FROM A, B
WHERE A.CODE = B.CODE; 

SELECT A.CODE, A.VAL, B.CODE, B.UNIT 
FROM A INNER JOIN B ON A.CODE = B.CODE;

SELECT A.CODE, A.VAL, B.CODE, B.UNIT 
FROM A JOIN B ON A.CODE = B.CODE;

--자연조인(NATURAL JOIN)
--자동으로 똑같은 컬럼을 찾아서 조인하고 중복된 컬럼을 제거해서 조회
SELECT * FROM A NATURAL JOIN B;

--교차 조인(CROSS JOIN)
--두 테이블의 모든 조합을 조회
SELECT * FROM A CROSS JOIN B;

--학생 테이블에 학과명만 중복없이 조회
SELECT DISTINCT STD_MAJOR FROM STUDENT;
--학과명, 행번호
SELECT 
	TO_CHAR(ROWNUM,'FM00') AS MAJOR_NO, 
	STD_MAJOR AS MAJOR_NAME 
FROM (SELECT DISTINCT STD_MAJOR FROM STUDENT);
--학과 테이블 생성
CREATE TABLE MAJOR
AS
SELECT 
	TO_CHAR(ROWNUM,'FM00') AS MAJOR_NO, 
	STD_MAJOR AS MAJOR_NAME 
FROM (SELECT DISTINCT STD_MAJOR FROM STUDENT);
--학생 테이블에 학과 번호 컬럼을 추가





