-- 관리자 계정으로 진행 - root
-- DB 생성
CREATE DATABASE SCOTT DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;
SHOW DATABASES;
DROP DATABASE SCOTT;
#DB 문자코드 변경
ALTER DATABASE 디비명 DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

# 계정생성
CREATE USER 'SCOTT'@'%' IDENTIFIED BY '123456';
#모든 권한 부여
GRANT ALL PRIVILEGES ON SCOTT.* TO 'SCOTT'@'%';
#권한 회수 방법
REVOKE ALL PRIVILEGES ON SCOTT.* FROM 'SCOTT'@'%';





